#!/usr/bin/env bash

pushd "$(dirname "$0")"
for file in *.js
do
  rm -rf copy.db
  printf "%s\t(%s)\n" "`{ gtime -f "%es / %P" node "$file"; } 2>&1`" "${file%.*}"
done
rm -rf copy.db

# 111.49s / 14% (fs::copyFile)
# 110.19s / 14% (fs::copyFileSync)
# 106.25s / 14% (bsd::copyfile)
#
# 128.81s / 95% (c++::fstream)
# 85.77s / 80%  (fs::stream)
# 81.18s / 81%  (db::backup)
#
# 82.40s / 62%  (c::fopen)
# 78.69s / 43%  (posix::open)

# compare different values of BUFFER_SIZE (for open and fopen)
# try PAGE_SIZE = 1 (for fopen)
